### ISSUE TITLE
Is "How long does it take for a translation to become available?"'s reply to be updated?

### ISSUE THREAD

**Issue by lidialab** [pedro-mendonca/Translation-Stats#124]
Hi Pedro,
great work!

In the Readme, the reply to "How long does it take for a translation to become available?" has to be updated with new threshold of 90%?
I also suggest to add that the translations have to be also approved.
-->
"when 90% of the Stable (latest release) sub-project strings have been translated and approved."

Ciao, Lidia

**Comment by pedro-mendonca** [comment]
You're correct, this threshold is outdated.
Thanks @lidialab for the reminder!

Fixed in https://github.com/pedro-mendonca/Translation-Stats/commit/67f656e0955801ca81548ffa1e8ca89bb917c5c8
