### ISSUE TITLE
Adding a class autoloader

### ISSUE THREAD

**Issue by szepeviktor** [pedro-mendonca/Translation-Stats#34]
Would you welcome a PR that adds Composer autoloader?

It would not require Composer - the tool - itself for running the plugin.

A whole lot of `require`-s would go!

**Comment by szepeviktor** [comment]
> `new TStats_Main();`

...plus you could have clean class files without side-effects.

**Comment by szepeviktor** [comment]
And introducing `TStats\` namespace would be great.

**Comment by pedro-mendonca** [comment]
Thanks @szepeviktor for your help :)

Yes, ```TStats``` namespacing is also on my TODOs :)
At the same time I'm realy thinking of cleaning class files and separating some more things.
The plugin scope and functionality have been growing a bit, some more ideas to come, and I do feel it needs to be restructered ahead.

I do appreciate your help and interest, feel free to contribute with Issues, PRs and ideas :)

**Comment by pedro-mendonca** [comment]
Class autoloader added in [version 0.9.6](https://github.com/pedro-mendonca/Translation-Stats/releases/tag/0.9.6)

**Comment by szepeviktor** [comment]
Thank you.
https://github.com/pedro-mendonca/Translation-Stats/blob/b4aa5cee958cf5759d2c0934f12f6debb6b6b053/translation-stats.php#L178-L205

**Comment by pedro-mendonca** [comment]
Thank you too :-)
