### ISSUE TITLE
Remove funcion name prefixes inside classes

### ISSUE THREAD

**Issue by szepeviktor** [pedro-mendonca/Translation-Stats#52]
You may begin with

`find -name "*.php" | xargs -L1 sed -i -e 's#function tstats_#function #'`

**Comment by szepeviktor** [comment]
And also for variables inside classes. `$tstats_`

**Comment by pedro-mendonca** [comment]
Good idea, must check each case to avoid ambiguous names.

**Comment by szepeviktor** [comment]
PHPStan has 100 👀 on you!

**Comment by pedro-mendonca** [comment]
Closing this for now, as all the prefixes of methods and variables inside classes were removed in https://github.com/pedro-mendonca/Translation-Stats/commit/8260cb3b43061fbeb66a8e35ef74aef12c6724cd.
Releasing in v.1.2.0

**Comment by szepeviktor** [comment]
Okay!
