### ISSUE TITLE
Please remove large colored blocks

### ISSUE THREAD

**Issue by Irinashl** [pedro-mendonca/Translation-Stats#529]
Remove large colored blocks

**Comment by pedro-mendonca** [comment]
For future self, this is what @Irinashl means by "colored blocks", the info-notice about the percentage of translation and language-packs generation.

![imagem](https://github.com/pedro-mendonca/Translation-Stats/assets/7371591/11d11800-a28f-4159-8f93-7dd626cb74e6)
![imagem](https://github.com/pedro-mendonca/Translation-Stats/assets/7371591/839f640e-e8e4-45b7-8c84-10691c3909eb)

I'll change the behaviour to show just on `WP_DEBUG` -> `true`

**Comment by pedro-mendonca** [comment]
Issue addressed in https://github.com/pedro-mendonca/Translation-Stats/commit/3dd0b2e6dfb8e64817b11aba5f99f241f2b5b57e
