### ISSUE TITLE
Mark plugin not properly prepared for localization

### ISSUE THREAD

**Issue by Irinashl** [pedro-mendonca/Translation-Stats#540]
Please mark a plugin that is not properly prepared for localization, for example, highlight it in red or short text.
example: Testerwp ecommerce companion - https://translate.wordpress.org/projects/wp-plugins/testerwp-ecommerce-companion/
Thanks

**Comment by pedro-mendonca** [comment]
The plugins are marked as you mention,
Since https://github.com/pedro-mendonca/Translation-Stats/issues/529 now it only shows when WP_DEBUG is true.

![imagem](https://github.com/pedro-mendonca/Translation-Stats/assets/7371591/fafb6cd8-6971-452b-ba1d-03a8b3f3e7dd)

**Comment by Irinashl** [comment]
Ok!

**Comment by pedro-mendonca** [comment]
On #557 I've changed the beahavior, the error notices like the info on plugins not prepared for localization are always shown now, despite the WP_DEBUG.
Released on v1.3.1
