### ISSUE TITLE
Function wp_kses_post invoked with 2 parameters, 1 required

### ISSUE THREAD

**Issue by szepeviktor** [pedro-mendonca/Translation-Stats#6]
```
 ------ --------------------------------------------------------------
  Line   translation-stats.php
 ------ --------------------------------------------------------------
  117    Function wp_kses_post invoked with 2 parameters, 1 required.
  139    Function wp_kses_post invoked with 2 parameters, 1 required.
 ------ --------------------------------------------------------------
```

powered by @phpstan

**Comment by pedro-mendonca** [comment]
Thanks @szepeviktor for the report.
Sorry for the late review :)

Fixed in https://github.com/pedro-mendonca/Translation-Stats/commit/a6db21695b4c88b9d394521cc883f42254a1a34c

**Comment by szepeviktor** [comment]
Thank you.
Please consider running @phpstan

**Comment by pedro-mendonca** [comment]
It's on my TO-DOs :)

**Comment by pedro-mendonca** [comment]
Hi @szepeviktor,
Is https://github.com/szepeviktor/phpstan-wordpress useful for WordPress constants like WP_LANG_DIR?

**Comment by szepeviktor** [comment]
Hello!
As in the README.

> Avoid using core constants, use core functions or MYPLUGIN_PATH

I think `WP_LANG_DIR` has no core function, use the constant.
It should be defined in a bootstrap file e.g. `tests/phpstan/bootstrap.php` and included in `autload_files:`

**Comment by szepeviktor** [comment]
Some constants are defined in the extension: https://github.com/szepeviktor/phpstan-wordpress/blob/master/bootstrap.php

**Comment by pedro-mendonca** [comment]
Maybe using [wp_lang_dir()](https://github.com/WordPress/WordPress/blob/master/wp-admin/includes/class-wp-filesystem-base.php#L115), not quite sure how yet.

**Comment by szepeviktor** [comment]
:) it also contains `WP_LANG_DIR`

**Comment by pedro-mendonca** [comment]
This fixes it: https://github.com/pedro-mendonca/Translation-Stats/commit/00f78bdb1db2a41be27915883f941ea326634c26

**Comment by szepeviktor** [comment]
It is a solution but it feels very strange to program in WordPress: function names loking like class names and globals :(

**Comment by pedro-mendonca** [comment]
It’s a huge code base, patched everywhere, with backwards compatibility in mind.
Still, if using WP constants is bad ideia, maybe something like wp_get_lang_dir() should exist.
